### ISSUE TITLE
Authentication group is empty

### ISSUE THREAD

**Issue by Eon9D** [anklimsk/wpkg-express-2#1]
First of all .. THANK YOU .. for keeping this great project alive (and even improving it)!

I've installed it but I am stuck at the last step:
"Fill in the fields in the Authentication group settings and click the Save button."

It is empty. How can I troubleshoot? Any ideas?

**Comment by Eon9D** [comment]
I was using 1.0.9 and testet 1.0.7;LDAP V2 and V3 - same problem.
I can see requests on the DC.
Logs under app/tmp/logs are empty.

**Comment by Eon9D** [comment]
Issue went away without a change after multiple reinstalls..

**Comment by anklimsk** [comment]
Good day. Fixed in a new release: [v1.0.12](https://github.com/anklimsk/wpkg-express-2/releases/tag/v1.0.12)
