### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by flagoda** [anklimsk/wpkg-express-2#10]
Hi,
First of all, thanks for extend support of wpkg-express with your fork.
This is not an issue, but improvement : can you add screenshots of your wpkg-express-2 in the readme.md ? This to give an idea

**Comment by anklimsk** [comment]
Hi! Thanks for the idea! I will try to make a presentation of the project. How everything will be ready, I will let you know.

**Comment by anklimsk** [comment]
Good day. I created a presentation: https://anklimsk.github.io/wpkg-express-2/presentation/

**Comment by anklimsk** [comment]
Hi! I added a slideshow of the [project](https://anklimsk.github.io/wpkg-express-2/).
