### ISSUE TITLE
dispatch( new CakeRequest(), new CakeResponse() );

### ISSUE THREAD

**Issue by flagoda** [anklimsk/wpkg-express-2#11]
Hi,
I try to install (new install) of the RC1.
But after installer my webpage show this : 
`dispatch( new CakeRequest(), new CakeResponse() );`
Have you idea ?

Regards

**Comment by anklimsk** [comment]
Hi! I checked the work on PHP version 7.4.3 - everything works. I do not have enough information:
what is your version of PHP;
what are the steps to repeat the error;
try turning on debugging [mode](https://github.com/anklimsk/wpkg-express-2/wiki/Enabling-debug-mode);
check the errors on the page and the file "app/tmp/logs/error.log".

**Comment by flagoda** [comment]
Sorry i have abandoned :/ To complicated for me i don't workmanship of CakePHP
