### ISSUE TITLE
Password reset/wrong

### ISSUE THREAD

**Issue by chlangbein** [anklimsk/wpkg-express-2#13]
Hello,
just tested wpkgexpress2 yesterday. Today I want to login again with local authentication user admin, but it's not possible. Maybe I typed password wrong or had some other problem on first steps.
So for now I'm looking for a solution to reset password. Tried to set *'IntAuthPassword' => ''*, but I'm not able to access settings. As I've created several xml templates, how to reset my password ?

Thanks in advance,
Christoph

**Comment by chlangbein** [comment]
Fixed this changing *app/Controller/Component/Auth/InternalAuthenticate.php* to return success and changed pass. Looks if you change anything in application settings you have to set all passwords.

**Comment by anklimsk** [comment]
Good day. Fixed in a new release: [v1.0.12](https://github.com/anklimsk/wpkg-express-2/releases/tag/v1.0.12)
