### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Eon9D** [anklimsk/wpkg-express-2#15]
I couldn't find any information on how to upgrade between versions.
Can you add a small paragraph to the Readme.md?

Thank you!

**Comment by anklimsk** [comment]
Hi! Check out the Wiki: [Update frontend to WPKG](https://github.com/anklimsk/wpkg-express-2/wiki/Update-frontend-to-WPKG)

**Comment by anklimsk** [comment]
Hi! I have updated the WiKi [page](https://github.com/anklimsk/wpkg-express-2/wiki/Update-frontend-to-WPKG)
