### ISSUE TITLE
Negative exitcodes

### ISSUE THREAD

**Issue by Eon9D** [anklimsk/wpkg-express-2#2]
Is it possible to add the possibility to add negative exitcodes?
In the old version this was possible - and we have a lot setups with negative numbers (Microsoft returns non critical negative numbers as information values).

Thanks

**Comment by Eon9D** [comment]
Okay, thank you for the quick answer!

Good job!

**Comment by adelphi-company** [comment]
So what is the solution here? Negative exit codes are not unusual, expecially for MSI.

Example:
Exit code returned non-successful value (-2146869246) on command '%COMSPEC% /c if exist "%ProgramFiles(x86)%" wusa.exe %SOFTWARE%\kb2642357\Windows6.1-KB2642357-x64.msu /quiet /norestart'.

The meaning of "-2146869246" is "TRUST_E_NO_SIGNER_CERT" (see https://www.magnumdb.com/search?q=-2146869246).


See https://www.magnumdb.com/search?q=-2146869246

**Comment by anklimsk** [comment]
Good day. Fixed in a new release: [v1.0.10-rc.1](https://github.com/anklimsk/wpkg-express-2/releases/tag/v1.0.10-rc.1)
