### ISSUE TITLE
Is it works with PHP 7.3 & MariaDB 10.3 ?

### ISSUE THREAD

**Issue by flagoda** [anklimsk/wpkg-express-2#3]
Hi,
This is not an issue, but is it works with Debian 9/10 : PHP 7.3 & MariaDB 10.3 ?
And is it work if we set CakePHP version 3 ?

Thanks

**Comment by anklimsk** [comment]
Hi!
I checked it on:
- PHP versions 5.6.33 and 7.0.33;
- MariaDB version 10.1.38.
This project is written on the CakePHP version 2 framework. CakePHP version 2 [support PHP above 7.1](https://book.cakephp.org/2.0/en/installation.html#requirements)

**Comment by flagoda** [comment]
Hi Thanks !
It is planned to be compatible with CakePHP 3 in the future ?

**Comment by anklimsk** [comment]
Hi! I plan to rewrite this project, but not in the near future.
