### ISSUE TITLE
"last modified" not always updating

### ISSUE THREAD

**Issue by adelphi-company** [anklimsk/wpkg-express-2#4]
If I change a variable value within a package, the "last modified" info doesn't update. This is very irritating if you link the revision of a package to a variable.

Repro:
- verify "last modified" timestamp of a package with variables (tab externded information)
- edit this package and only change a value if a variable within tab variables
- verify "last modified" timestamp the package -> it did not change
- modify somethign alse, e.g. the "notes" -> "last modified" gets updated.

**Comment by anklimsk** [comment]
Hi! The timestamp of the last change is updated only when the basic information changes, for example, identifier or name (after performing "add" or "edit" actions for a package, profile, or host).

**Comment by anklimsk** [comment]
Good day. Fixed in a new release: [v1.1.0-rc.1](https://github.com/anklimsk/wpkg-express-2/releases/tag/v1.1.0-rc.1)
