### ISSUE TITLE
Revision doesn't show variable values

### ISSUE THREAD

**Issue by adelphi-company** [anklimsk/wpkg-express-2#5]
In almost every package we are using variables for the version numbers of the software. This limits the neccesary changes on each update (package revision, file version check, file name in command). and is IMHO best practice.

Unfortunately the list view for packages shows the variable name (e.g. %version%) only and therefore it's not possible to quickly check the package version. I have to open each package to get the real version (see Screenshot)
![Screenshot](https://user-images.githubusercontent.com/50949310/58246190-b4790400-7d56-11e9-8ede-8888378d826c.png)

Can you change the list view to replace variables by their values?

**Comment by anklimsk** [comment]
Hi! In the "revision" field of the package, you must specify the current revision of the package. If the setting "Auto variable %Revision%" is enabled, the variables %Revision% and %RevI1%,... should be used (automatically updated when the package revision is changed).
