### ISSUE TITLE
Postgres incompatibilities

### ISSUE THREAD

**Issue by hanseltime** [anklimsk/wpkg-express-2#6]
When trying to set the CakePHP database to a postgres 9.6 or postgres 9.4, in the post-install actions I get this exception:

Error: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ""Package""
LINE 1: ...M "public"."packages" AS "Package"   WHERE BINARY "Package"....
                                                             ^
>#0 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Datasource\DboSource.php(502): PDOStatement->execute(Array)
>#1 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Datasource\DboSource.php(468): DboSource->_execute('SELECT COUNT(*)...', Array)
>#2 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Datasource\DboSource.php(715): DboSource->execute('SELECT COUNT(*)...', Array, Array)
>#3 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Datasource\DboSource.php(1226): DboSource->fetchAll('SELECT COUNT(*)...', Array)
>#4 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(3053): DboSource->read(Object(Package), Array)
>#5 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(3025): Model->_readDataSource('count', Array)
>#6 C:\PHP\Wpkg-express-2\app\Model\Behavior\ValidationRulesBehavior.php(137): Model->find('count', Array)
>#7 C:\PHP\Wpkg-express->2\vendors\cakephp\cakephp\lib\Cake\Model\BehaviorCollection.php(238): ValidationRulesBehavior->isUniqueID(Object(Package), Array, Array)
>#8 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(829): BehaviorCollection->dispatchMethod(Object(Package), Array, Array)
>#9 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Validator\CakeValidationRule.php(275): Model->__call('isUniqueID', Array)
>#10 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Validator\CakeValidationSet.php(135): CakeValidationRule->process('id_text', Array, Array)
>#11 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\ModelValidator.php(268): CakeValidationSet->validate(Array, false)
>#12 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\ModelValidator.php(99): ModelValidator->errors(Array)
>#13 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(3502): ModelValidator->validates(Array)
>#14 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(1838): Model->validates(Array)
>#15 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(1760): Model->_doSave(Array, Array)
>#16 C:\PHP\Wpkg-express-2\app\Model\AppModel.php(106): Model->save(Array, true, Array)
>#17 C:\PHP\Wpkg-express-2\app\Model\Import.php(2464): AppModel->save(Array)
>#18 C:\PHP\Wpkg-express-2\app\Model\Import.php(2504): Import->_saveInfoPackage(Array, Array)
>#19 C:\PHP\Wpkg-express-2\app\Model\Import.php(1142): Import->_savePackage(Array, Array)
>#20 C:\PHP\Wpkg-express-2\app\Model\Import.php(3658): Import->importXmlPackages('C:\\PHP\\Wpkg-exp...', NULL)
>#21 C:\PHP\Wpkg-express-2\app\Model\InstallerCompleted.php(84): Import->importXml('C:\\PHP\\Wpkg-exp...')
>#22 C:\PHP\Wpkg-express-2\app\Plugin\CakeInstaller\Console\Command\CakeInstallerShell.php(549): InstallerCompleted->intsallCompleted()
>#23 C:\PHP\Wpkg-express-2\app\Plugin\CakeInstaller\Console\Command\CakeInstallerShell.php(308): CakeInstallerShell->_install()
>#24 C:\PHP\Wpkg-express-2\app\Plugin\CakeInstaller\Console\Command\CakeInstallerShell.php(240): CakeInstallerShell->install()
>#25 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Console\Shell.php(462): CakeInstallerShell->main()
>#26 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(222): Shell->runCommand(NULL, Array)
>#27 C:\PHP\Wpkg-express-2\vendors\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
>#28 C:\PHP\Wpkg-express-2\app\Console\cake.php(47): ShellDispatcher::run(Array)
>#29 {main}

Details about setup:

* Using php 7.3.6
* CakePHP was upgraded to 2.* (latest)
* Postgresql DBs tested were 9.6 and 9.4
** User has full permission
** Schema used is public
* SQL query in question:
** "SELECT COUNT(*) AS "count" FROM "public"."packages" AS "Package"   WHERE BINARY "Package"."id_text" = 'PACKAGE_TEMPLATE_MSI_SIMPLE'"

This looks to be the result of the ValidationRulesBehavior->isUniqueID().  When commenting out `[127] $binary='Binary';` I can circumvent this error.  It seems that the query does not resolve in Postgres due to syntax.  To my knowledge, string comparison in postgres is case-sensitive and a case-insensitive solution with Postgres is LOWER()=LOWER().  I have tested the non-binary and Lower versions of the search and they seem to not throw parse errors.

**Comment by anklimsk** [comment]
Good day. Fixed in a new release: [v1.0.10-rc.1](https://github.com/anklimsk/wpkg-express-2/releases/tag/v1.0.10-rc.1)
