### ISSUE TITLE
cron errors after php7.0 -> 7.3 update

### ISSUE THREAD

**Issue by adelphi-company** [anklimsk/wpkg-express-2#7]
After upgrade from Debian 9 with php7.0 to Debian 10 with php7.3, the cron job 
`cd /var/www/wpkg2/app/ && Console/cake Queue.Queue runworker -q`
 generates following errors:

> Warning Error: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in [/var/www/wpkg2/app/Model/Behavior/GroupActionBehavior.php, line 145]
> 
> 2019-07-25 10:50:01 Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in [/var/www/wpkg2/app/Model/Behavior/GroupActionBehavior.php, line 145] Warning Error: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in [/var/www/wpkg2/app/Plugin/CakeSettingsApp/Model/SettingBase.php, line 627]
> 
> 2019-07-25 10:50:01 Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in [/var/www/wpkg2/app/Plugin/CakeSettingsApp/Model/SettingBase.php, line 627]

Any ideas?

**Comment by adelphi-company** [comment]
Possible solution:

Replace "continue;" by "break;" in
/var/www/wpkg2/app/Model/Behavior/GroupActionBehavior.php, line 145
/var/www/wpkg2/app/Plugin/CakeSettingsApp/Model/SettingBase.php, line 627
?

**Comment by anklimsk** [comment]
Good day. Fixed in a new release: [v1.0.10-rc.1](https://github.com/anklimsk/wpkg-express-2/releases/tag/v1.0.10-rc.1)
