### ISSUE TITLE
Не сохраняются настройки

### ISSUE THREAD

**Issue by lumian** [anklimsk/wpkg-express-2#8]
Здравствуйте!
В расширенных настройках никак не получается записать настройки для "Разбор журналов и баз данных клиентов". Ввожу данные, сохраняю, далее сверху идет загрузка, обновляется страница, введенные данные на месте. Обновляю страницу - поля пустые.

Как можно пофиксить?

**Comment by anklimsk** [comment]
Доброго дня! Мне сложно что-либо сказать однозначно, но, попробуем разобраться. Итак, по-порядку:
1) Не обновляется вся информация или только поле "Разбор журналов и баз данных клиентов"? Информация о настройках сохраняется в файле «app/Config/config.php». Если файл обновился (настройка «WPKG/SmbLogShare»), но на странице настроек изменений нет — возможно, на сервере работает кэш, на подобии, opcache. Также при сохранении этого поля происходит [проверка настроек SMB клиента](https://github.com/anklimsk/wpkg-express-2/blob/bf0988a01e07995c2e8c5766abb2d9cf466a7413/app/Model/Setting.php#L157). Тогда, возможно, вы ошиблись в настройках: имени пользователя, пароле, сервере, шаре, или рабочей группе (домене). Также, проверьте, установлен ли у вас на сервере «smbclient», и всё ли с ним в порядке (попробуйте подключиться к шаре с логами из консоли).
2) Попробуйте включить [режим отладки](https://github.com/anklimsk/wpkg-express-2/wiki/Enabling-debug-mode) и проверьте ошибки на странице и в файле "app/tmp/logs/error.log".

P. S. Извиняюсь за задержку с ответом. Просто у меня больше нет свободного времени, чтобы активно заниматься этим проектом.
